// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const HAS_VALID_ENV = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// En modo demo (sin variables), exponemos un cliente mock mínimo.
const createMockSupabase = () => {
  const subscription = { unsubscribe: () => {} };
  return {
    auth: {
      onAuthStateChange: (_cb: unknown) => ({ data: { subscription } }),
      getSession: async () => ({ data: { session: null } }),
      signInWithPassword: async () => ({ error: new Error("Mock auth: sin backend") }),
      signUp: async () => ({ error: new Error("Mock auth: sin backend") }),
      signOut: async () => ({ error: null }),
    },
  } as unknown as ReturnType<typeof createClient<Database>>;
};

export const supabase = HAS_VALID_ENV
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    })
  : createMockSupabase();